# ============================================================
# Auto Setup Script untuk Apache Virtual Host
# Query Report API
# ============================================================
# Run as Administrator
# ============================================================

Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "Query Report API - Apache Setup" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""

# Path Configuration
$projectPath = "C:/PROJEK/API/queryreport-api"
$xamppPath = "C:/xampp"
$httpd_conf = "$xamppPath/apache/conf/httpd.conf"
$vhosts_conf = "$xamppPath/apache/conf/extra/httpd-vhosts.conf"

# Check if XAMPP exists
if (-not (Test-Path $xamppPath)) {
    Write-Host "ERROR: XAMPP tidak ditemukan di $xamppPath" -ForegroundColor Red
    Write-Host "Install XAMPP terlebih dahulu atau ubah path di script ini." -ForegroundColor Yellow
    exit
}

Write-Host "[1/5] Checking XAMPP installation... OK" -ForegroundColor Green

# Backup vhosts config
Write-Host "[2/5] Creating backup of httpd-vhosts.conf..." -ForegroundColor Yellow
Copy-Item $vhosts_conf "$vhosts_conf.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')" -Force
Write-Host "      Backup created!" -ForegroundColor Green

# Virtual Host Configuration
$vhostConfig = @"

# ============================================================
# Query Report API - Auto Generated by Setup Script
# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# ============================================================
<VirtualHost *:8080>
    DocumentRoot "$projectPath/public"
    
    <Directory "$projectPath/public">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
        
        # Enable rewrite
        RewriteEngine On
        
        # Redirect to index.php if not a file or directory
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)$ index.php/`$1 [L]
    </Directory>
    
    # CORS Headers
    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
    Header always set Access-Control-Allow-Headers "Content-Type, Authorization, X-Requested-With"
    
    # Logging
    ErrorLog "$projectPath/writable/logs/apache-error.log"
    CustomLog "$projectPath/writable/logs/apache-access.log" combined
</VirtualHost>

"@

# Add Virtual Host Configuration
Write-Host "[3/5] Adding Virtual Host configuration..." -ForegroundColor Yellow
Add-Content -Path $vhosts_conf -Value $vhostConfig
Write-Host "      Virtual Host added!" -ForegroundColor Green

# Check if Include is enabled
Write-Host "[4/5] Checking httpd.conf for vhosts include..." -ForegroundColor Yellow
$httpdContent = Get-Content $httpd_conf -Raw
if ($httpdContent -match "#\s*Include conf/extra/httpd-vhosts.conf") {
    Write-Host "      WARNING: httpd-vhosts.conf is commented out!" -ForegroundColor Yellow
    Write-Host "      Uncommenting..." -ForegroundColor Yellow
    
    $httpdContent = $httpdContent -replace "#\s*Include conf/extra/httpd-vhosts.conf", "Include conf/extra/httpd-vhosts.conf"
    Set-Content -Path $httpd_conf -Value $httpdContent
    Write-Host "      Include enabled!" -ForegroundColor Green
}
else {
    Write-Host "      Include already enabled!" -ForegroundColor Green
}

# Restart Apache
Write-Host "[5/5] Restarting Apache..." -ForegroundColor Yellow
Write-Host "      Please restart Apache manually from XAMPP Control Panel" -ForegroundColor Cyan
Write-Host ""

# Summary
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "1. Open XAMPP Control Panel" -ForegroundColor White
Write-Host "2. Stop Apache (if running)" -ForegroundColor White
Write-Host "3. Start Apache" -ForegroundColor White
Write-Host ""
Write-Host "Test URL:" -ForegroundColor Yellow
Write-Host "  Local:   http://localhost:8080/api/login" -ForegroundColor White
Write-Host "  Network: http://192.168.30.70:8080/api/login" -ForegroundColor White
Write-Host ""
Write-Host "Postman Test:" -ForegroundColor Yellow
Write-Host '  POST http://192.168.30.70:8080/api/login' -ForegroundColor White
Write-Host '  Body: {"username":"admin","password":"admin123"}' -ForegroundColor White
Write-Host ""

# Firewall Rule
Write-Host "Optional - Add Firewall Rule (Run as Administrator):" -ForegroundColor Yellow
Write-Host '  netsh advfirewall firewall add rule name="Apache 8080" dir=in action=allow protocol=TCP localport=8080' -ForegroundColor Gray
Write-Host ""
